### ISSUE TITLE
Creazione tesserino errore: manca rejex

### ISSUE THREAD

**Issue by AngelaDeM** [CFerrara98/DigitalDonation#32]
In creazione tesserino, in altre indicazioni, quando s'inserisce @@@ non lancia il seguente errore "Altre indicazioni non rispetta il formato. Inserire caratteri alfanumerici e punteggiatura".

**Comment by kevinpcf** [comment]
In realtà è una scelta nostra, perché l'operatore può inserire caratteri speciali, come ad esempio "Dott." o una mail di riferimento per delle problematiche
