### ISSUE TITLE
Modal di successo per l'inserimento seduta

### ISSUE THREAD

**Issue by CFerrara98** [CFerrara98/DigitalDonation#7]
Quando una seduta viene scheulata con successo, è necessario creare un feedback grafico quando l'utente viene reindirizzato alla dashbord @Elpiu @Zengr098 @kevinpcf @Elpiu

**Comment by Elpiu** [comment]
![sedutra successo](https://user-images.githubusercontent.com/49283847/147951813-de1f842c-4e4c-41df-92b9-3aa4205f5b41.jpg)
Issure chiusa da @marikaspagnazito @FabioSiepe
